name: Deploy React + Vite to Github Pages

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pages: write

        steps:
            # Checkout the repository
            - name: Checkout code
              uses: actions/checkout@v4

            # Setup Bun
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            # Cache dependencies
            - name: Cache Bun dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock', '**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            # Install Dependencies
            - name: Install Dependencies
              run: bun install --frozen-lockfile

            # Run linting and type checking
            - name: Run linting
              run: bun run lint

            # Install ffmpeg
            - name: Install ffmpeg
              run: sudo apt-get update && sudo apt-get install -y ffmpeg

            # Build the project
            - name: Build project
              run: bun run build

            # Deploy to github pages
            - name: Deploy to github pages
              if: github.ref == 'refs/heads/main'
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: dist
